name: dio_interceptor_seq
description: An interceptor for the DIO client that sends request, response, and error logs to Seq.
version: 2.0.1
homepage: https://github.com/Altamir/dio_interceptor_seq

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.1.1 
  http: ^1.1.0
  uuid: ^3.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: 
  build_runner:
  flutter_lints: 
  flutter_test:
    sdk: flutter


flutter:

