name: dio_interceptor_seq
description: An interceptor for the DIO client that sends request, response, and error logs to Seq.
version: 0.0.1
homepage: https://github.com/Altamir/dio_interceptor_seq

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.0
  http: ^0.13.3
  uuid: ^3.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: 
  build_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:

